
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Notebook notebook2;

	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button btnOpenPlayerDat;

	private global::Gtk.Button btnSave;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label1;

	private global::Gtk.ComboBox cmbScene;

	private global::Gtk.Frame frame3;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label label4;

	private global::Gtk.HScale hsAct;

	private global::Gtk.Label label6;

	private global::Gtk.HScale hsDay;

	private global::Gtk.CheckButton chkNight;

	private global::Gtk.Label GtkLabel3;

	private global::Gtk.Frame frame4;

	private global::Gtk.Alignment GtkAlignment1;

	private global::Gtk.Label lblBandPractice;

	private global::Gtk.Label GtkLabel6;

	private global::Gtk.Frame frame5;

	private global::Gtk.Alignment GtkAlignment2;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Frame frame6;

	private global::Gtk.Alignment GtkAlignment3;

	private global::Gtk.VBox vbox4;

	private global::Gtk.CheckButton chkSelmers;

	private global::Gtk.CheckButton chkStargazer;

	private global::Gtk.CheckButton chkPentagrams;

	private global::Gtk.CheckButton chkBirdquest;

	private global::Gtk.CheckButton chkTooth;

	private global::Gtk.CheckButton chkMomFriendship;

	private global::Gtk.CheckButton chkGermFriendship;

	private global::Gtk.CheckButton chkMiracleBabies;

	private global::Gtk.Label GtkLabel21;

	private global::Gtk.Frame frame7;

	private global::Gtk.Alignment GtkAlignment4;

	private global::Gtk.VBox vbox5;

	private global::Gtk.CheckButton chkBeaFriendship;

	private global::Gtk.CheckButton chkGreggFriendship;

	private global::Gtk.CheckButton chkBeaGhostHunting;

	private global::Gtk.CheckButton chkGreggGhostHunting;

	private global::Gtk.CheckButton chkAngusGhostHunting;

	private global::Gtk.Label GtkLabel22;

	private global::Gtk.Label GtkLabel18;

	private global::Gtk.Label label2;

	private global::Gtk.VBox vbox2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView treeVars;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Label label7;

	private global::Gtk.Entry txtValueName;

	private global::Gtk.Button btnInsertRaw;

	private global::Gtk.Button btnDeleteRaw;

	private global::Gtk.Label label3;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Night in the Woods Save Editor");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.Gravity = ((global::Gdk.Gravity)(5));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.notebook2 = new global::Gtk.Notebook();
		this.notebook2.CanDefault = true;
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 0;
		this.notebook2.Scrollable = true;
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnOpenPlayerDat = new global::Gtk.Button();
		this.btnOpenPlayerDat.CanFocus = true;
		this.btnOpenPlayerDat.Name = "btnOpenPlayerDat";
		this.btnOpenPlayerDat.UseUnderline = true;
		this.btnOpenPlayerDat.Label = global::Mono.Unix.Catalog.GetString("Open player.dat");
		this.hbox2.Add(this.btnOpenPlayerDat);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnOpenPlayerDat]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnSave = new global::Gtk.Button();
		this.btnSave.Sensitive = false;
		this.btnSave.CanFocus = true;
		this.btnSave.Name = "btnSave";
		this.btnSave.UseUnderline = true;
		this.btnSave.Label = global::Mono.Unix.Catalog.GetString("Save player.dat");
		this.hbox2.Add(this.btnSave);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnSave]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		this.hbox1.BorderWidth = ((uint)(5));
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Scene selection");
		this.hbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.cmbScene = global::Gtk.ComboBox.NewText();
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Logos"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Title"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("IntroPoem"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("DemoLogos"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("DemoTitle"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Demo2Logos"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Demo2Title"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Demo2End"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("BusStation"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("BusStationExterior"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Ravine"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Playground"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MaeRoom"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Mirror"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MaeHouse"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MaeHouseBasement"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MaeHouseCrawlspace"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MaeStreet"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Underhill"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("UnderhillLaundrySecret"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("TowneCentreEast"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("TowneCentreWest"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Bridge"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("GreggAngusApartmentLobby"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("GreggAngusApartment"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("GreggAngusApartmentHallway"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("GreggAngusParkingLot"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("BeaApartment"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("BeaRoom"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("HamPanther"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Videostore"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("OlPickaxe"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("PartyClearing"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SnackFalcon"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Outskirts"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("ChurchHill"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("ChurchHall"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("ChurchSanctuary"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Tunnel"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MallardsTomb"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("FoodDonkeyInterior"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Tracks"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("OverheadTracks"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("URev"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("FPS"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MusicStore"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("FortLucenneMall"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("BasementTunnel"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("ParkEntrance"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("ScoutCamp"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Library"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("BathroomMirror"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("BathroomVandalism"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MomQuest"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Birdland"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("CarryingRobotMascot"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("RobotBuilder"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("PossumJump"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Diner"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("BeaIQGraveyard"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("BeaIQOldSection"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("BeaIQTunnel1"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("BeaIQTunnel2"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MansionHistoryRoom"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MansionExterior"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MansionInterior"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MansionMapRoom"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MansionFireEscape"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("ParkingLot"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("GermHouse"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("GermKitchen"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("GermLivingRoom"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("GreggFQ3Woods"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Roadside"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("RoadsideClearing"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("DonutWolfInterior"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("GreggMaeBike"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("TowneCentreEast_Harfest"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Demontower"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("LockPicking"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("DTF0"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("DTF1"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("DTF2"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("DTF3"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("DTF4"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("DTF5"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("DTF6"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("DTF7"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("DTF8"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("DTF9"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("DTF10"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("DonutWolfExterior"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("PawsModeTowneCentreEastPS"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("PawsModeWindow"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("PawsModeMallard"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("PawsModeDonutWolf01"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("PawsModeDonutWolfGreggAngus"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("PawsModeDiner"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("PawsModeSeveredArm"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("PawsModeIntercom"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("PawsModeLookAtClouds"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("PawsModeStealing"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("PawsModeStealingPretzel"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("FixFurnace"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("PawsModeBatteryDisconnect"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("PawsModeBatteryConnect"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("PawsModeFlipTheSwitch"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Bird"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("PawsModeBeaCoffin"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("PawsModeMineBoards"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("PawsModePizzaParty"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("AngusConstellations"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("KnifeFight"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_Part1"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_Part2"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_Part3"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_Part4"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_Part5"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_GreggFQ1Intro"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_GreggFQ2Intro"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_GreggFQ3Intro"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_GreggFQ4Intro"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_BeaFQ1Intro"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_BeaFQ2Intro"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_BeaFQ3Intro"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_BeaFQ4Intro"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_AngusIQ"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_BeaIQ"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_GreggIQ"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_Harfest"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_TheDark"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_TheLibrary"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SectionTitle_TheParty"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("ShowJournalDoodles"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("BeaCar"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Laptop"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("AstralAct1Day3"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("AstralAct2Day1"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("AstralAct2Day2"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("AstralAct2Day3"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("BlackoutWoods"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("AstralAct3Day1"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("AstralAct3Day2"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("LongestNight"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Telescope"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Microfiche"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("CharacterRigs"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("Empty"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("TestAstralMovement"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("TestPawsMode"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MineWoods"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MineWoodsRunAway"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MineEntrance"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MineBottom1"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MineBottom2"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MineWellTunnel"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("WellWoods"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("DeathPrairie_Woods"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("DeathPrairie_Outskirts"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("DeathPrairie_MaeStreet"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MirandaYard"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MirandaHouse"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("MirandaBasement"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("BeaTown"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("BeaParty"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("GermVignette"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("FoodFlicker"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("BandPractice"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("LightBulbSmash"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("SharkleDream"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("EndCredits"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("EndCreditsPS4"));
		this.cmbScene.AppendText(global::Mono.Unix.Catalog.GetString("EndSharkle"));
		this.cmbScene.Sensitive = false;
		this.cmbScene.Name = "cmbScene";
		this.hbox1.Add(this.cmbScene);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.cmbScene]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Act");
		this.hbox3.Add(this.label4);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label4]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hsAct = new global::Gtk.HScale(null);
		this.hsAct.Sensitive = false;
		this.hsAct.CanFocus = true;
		this.hsAct.Name = "hsAct";
		this.hsAct.Adjustment.Upper = 4;
		this.hsAct.Adjustment.PageIncrement = 1;
		this.hsAct.Adjustment.StepIncrement = 1;
		this.hsAct.DrawValue = true;
		this.hsAct.Digits = 0;
		this.hsAct.ValuePos = ((global::Gtk.PositionType)(0));
		this.hbox3.Add(this.hsAct);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hsAct]));
		w8.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Day");
		this.hbox3.Add(this.label6);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label6]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hsDay = new global::Gtk.HScale(null);
		this.hsDay.Sensitive = false;
		this.hsDay.CanFocus = true;
		this.hsDay.Name = "hsDay";
		this.hsDay.Adjustment.Upper = 5;
		this.hsDay.Adjustment.PageIncrement = 1;
		this.hsDay.Adjustment.StepIncrement = 1;
		this.hsDay.DrawValue = true;
		this.hsDay.Digits = 0;
		this.hsDay.ValuePos = ((global::Gtk.PositionType)(0));
		this.hbox3.Add(this.hsDay);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hsDay]));
		w10.Position = 3;
		// Container child hbox3.Gtk.Box+BoxChild
		this.chkNight = new global::Gtk.CheckButton();
		this.chkNight.Sensitive = false;
		this.chkNight.CanFocus = true;
		this.chkNight.Name = "chkNight";
		this.chkNight.Label = global::Mono.Unix.Catalog.GetString("Night");
		this.chkNight.DrawIndicator = true;
		this.chkNight.UseUnderline = true;
		this.hbox3.Add(this.chkNight);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.chkNight]));
		w11.Position = 4;
		this.GtkAlignment.Add(this.hbox3);
		this.frame3.Add(this.GtkAlignment);
		this.GtkLabel3 = new global::Gtk.Label();
		this.GtkLabel3.Name = "GtkLabel3";
		this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString("Day selection");
		this.GtkLabel3.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel3;
		this.vbox1.Add(this.frame3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.frame3]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame();
		this.frame4.Name = "frame4";
		this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.lblBandPractice = new global::Gtk.Label();
		this.lblBandPractice.Name = "lblBandPractice";
		this.lblBandPractice.LabelProp = global::Mono.Unix.Catalog.GetString("No data");
		this.GtkAlignment1.Add(this.lblBandPractice);
		this.frame4.Add(this.GtkAlignment1);
		this.GtkLabel6 = new global::Gtk.Label();
		this.GtkLabel6.Name = "GtkLabel6";
		this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString("Band practice");
		this.GtkLabel6.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel6;
		this.vbox1.Add(this.frame4);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.frame4]));
		w17.Position = 3;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame5 = new global::Gtk.Frame();
		this.frame5.Name = "frame5";
		this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame5.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.frame6 = new global::Gtk.Frame();
		this.frame6.Name = "frame6";
		this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame6.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.chkSelmers = new global::Gtk.CheckButton();
		this.chkSelmers.CanFocus = true;
		this.chkSelmers.Name = "chkSelmers";
		this.chkSelmers.Label = global::Mono.Unix.Catalog.GetString("Listened to Selmers' poem");
		this.chkSelmers.DrawIndicator = true;
		this.chkSelmers.UseUnderline = true;
		this.vbox4.Add(this.chkSelmers);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.chkSelmers]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.chkStargazer = new global::Gtk.CheckButton();
		this.chkStargazer.CanFocus = true;
		this.chkStargazer.Name = "chkStargazer";
		this.chkStargazer.Label = global::Mono.Unix.Catalog.GetString("All dusk stars found");
		this.chkStargazer.DrawIndicator = true;
		this.chkStargazer.UseUnderline = true;
		this.vbox4.Add(this.chkStargazer);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.chkStargazer]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.chkPentagrams = new global::Gtk.CheckButton();
		this.chkPentagrams.CanFocus = true;
		this.chkPentagrams.Name = "chkPentagrams";
		this.chkPentagrams.Label = global::Mono.Unix.Catalog.GetString("All pentagrams found");
		this.chkPentagrams.DrawIndicator = true;
		this.chkPentagrams.UseUnderline = true;
		this.vbox4.Add(this.chkPentagrams);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.chkPentagrams]));
		w20.Position = 2;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.chkBirdquest = new global::Gtk.CheckButton();
		this.chkBirdquest.CanFocus = true;
		this.chkBirdquest.Name = "chkBirdquest";
		this.chkBirdquest.Label = global::Mono.Unix.Catalog.GetString("Musicians brought together");
		this.chkBirdquest.DrawIndicator = true;
		this.chkBirdquest.UseUnderline = true;
		this.vbox4.Add(this.chkBirdquest);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.chkBirdquest]));
		w21.Position = 3;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.chkTooth = new global::Gtk.CheckButton();
		this.chkTooth.CanFocus = true;
		this.chkTooth.Name = "chkTooth";
		this.chkTooth.Label = global::Mono.Unix.Catalog.GetString("Tooth shown to dad");
		this.chkTooth.DrawIndicator = true;
		this.chkTooth.UseUnderline = true;
		this.vbox4.Add(this.chkTooth);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.chkTooth]));
		w22.Position = 4;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.chkMomFriendship = new global::Gtk.CheckButton();
		this.chkMomFriendship.CanFocus = true;
		this.chkMomFriendship.Name = "chkMomFriendship";
		this.chkMomFriendship.Label = global::Mono.Unix.Catalog.GetString("Mom friendship");
		this.chkMomFriendship.DrawIndicator = true;
		this.chkMomFriendship.UseUnderline = true;
		this.vbox4.Add(this.chkMomFriendship);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.chkMomFriendship]));
		w23.Position = 5;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.chkGermFriendship = new global::Gtk.CheckButton();
		this.chkGermFriendship.CanFocus = true;
		this.chkGermFriendship.Name = "chkGermFriendship";
		this.chkGermFriendship.Label = global::Mono.Unix.Catalog.GetString("Germ friendship");
		this.chkGermFriendship.DrawIndicator = true;
		this.chkGermFriendship.UseUnderline = true;
		this.vbox4.Add(this.chkGermFriendship);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.chkGermFriendship]));
		w24.Position = 6;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.chkMiracleBabies = new global::Gtk.CheckButton();
		this.chkMiracleBabies.CanFocus = true;
		this.chkMiracleBabies.Name = "chkMiracleBabies";
		this.chkMiracleBabies.Label = global::Mono.Unix.Catalog.GetString("Miracle rats");
		this.chkMiracleBabies.DrawIndicator = true;
		this.chkMiracleBabies.UseUnderline = true;
		this.vbox4.Add(this.chkMiracleBabies);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.chkMiracleBabies]));
		w25.Position = 7;
		w25.Expand = false;
		w25.Fill = false;
		this.GtkAlignment3.Add(this.vbox4);
		this.frame6.Add(this.GtkAlignment3);
		this.GtkLabel21 = new global::Gtk.Label();
		this.GtkLabel21.Name = "GtkLabel21";
		this.GtkLabel21.LabelProp = global::Mono.Unix.Catalog.GetString("Make It Last");
		this.GtkLabel21.UseMarkup = true;
		this.frame6.LabelWidget = this.GtkLabel21;
		this.vbox3.Add(this.frame6);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.frame6]));
		w28.PackType = ((global::Gtk.PackType)(1));
		w28.Position = 0;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.frame7 = new global::Gtk.Frame();
		this.frame7.Name = "frame7";
		this.frame7.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame7.Gtk.Container+ContainerChild
		this.GtkAlignment4 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment4.Name = "GtkAlignment4";
		this.GtkAlignment4.LeftPadding = ((uint)(12));
		// Container child GtkAlignment4.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.chkBeaFriendship = new global::Gtk.CheckButton();
		this.chkBeaFriendship.CanFocus = true;
		this.chkBeaFriendship.Name = "chkBeaFriendship";
		this.chkBeaFriendship.Label = global::Mono.Unix.Catalog.GetString("Bea friendship");
		this.chkBeaFriendship.DrawIndicator = true;
		this.chkBeaFriendship.UseUnderline = true;
		this.vbox5.Add(this.chkBeaFriendship);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.chkBeaFriendship]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.chkGreggFriendship = new global::Gtk.CheckButton();
		this.chkGreggFriendship.CanFocus = true;
		this.chkGreggFriendship.Name = "chkGreggFriendship";
		this.chkGreggFriendship.Label = global::Mono.Unix.Catalog.GetString("Gregg friendship");
		this.chkGreggFriendship.DrawIndicator = true;
		this.chkGreggFriendship.UseUnderline = true;
		this.vbox5.Add(this.chkGreggFriendship);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.chkGreggFriendship]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.chkBeaGhostHunting = new global::Gtk.CheckButton();
		this.chkBeaGhostHunting.CanFocus = true;
		this.chkBeaGhostHunting.Name = "chkBeaGhostHunting";
		this.chkBeaGhostHunting.Label = global::Mono.Unix.Catalog.GetString("Bea ghost hunting");
		this.chkBeaGhostHunting.DrawIndicator = true;
		this.chkBeaGhostHunting.UseUnderline = true;
		this.vbox5.Add(this.chkBeaGhostHunting);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.chkBeaGhostHunting]));
		w31.Position = 2;
		w31.Expand = false;
		w31.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.chkGreggGhostHunting = new global::Gtk.CheckButton();
		this.chkGreggGhostHunting.CanFocus = true;
		this.chkGreggGhostHunting.Name = "chkGreggGhostHunting";
		this.chkGreggGhostHunting.Label = global::Mono.Unix.Catalog.GetString("Gregg ghost hunting");
		this.chkGreggGhostHunting.DrawIndicator = true;
		this.chkGreggGhostHunting.UseUnderline = true;
		this.vbox5.Add(this.chkGreggGhostHunting);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.chkGreggGhostHunting]));
		w32.Position = 3;
		w32.Expand = false;
		w32.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.chkAngusGhostHunting = new global::Gtk.CheckButton();
		this.chkAngusGhostHunting.CanFocus = true;
		this.chkAngusGhostHunting.Name = "chkAngusGhostHunting";
		this.chkAngusGhostHunting.Label = global::Mono.Unix.Catalog.GetString("Angus ghost hunting");
		this.chkAngusGhostHunting.DrawIndicator = true;
		this.chkAngusGhostHunting.UseUnderline = true;
		this.vbox5.Add(this.chkAngusGhostHunting);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.chkAngusGhostHunting]));
		w33.Position = 4;
		w33.Expand = false;
		w33.Fill = false;
		this.GtkAlignment4.Add(this.vbox5);
		this.frame7.Add(this.GtkAlignment4);
		this.GtkLabel22 = new global::Gtk.Label();
		this.GtkLabel22.Name = "GtkLabel22";
		this.GtkLabel22.LabelProp = global::Mono.Unix.Catalog.GetString("Hold Onto Everything");
		this.GtkLabel22.UseMarkup = true;
		this.frame7.LabelWidget = this.GtkLabel22;
		this.vbox3.Add(this.frame7);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.frame7]));
		w36.PackType = ((global::Gtk.PackType)(1));
		w36.Position = 1;
		w36.Expand = false;
		w36.Fill = false;
		this.GtkAlignment2.Add(this.vbox3);
		this.frame5.Add(this.GtkAlignment2);
		this.GtkLabel18 = new global::Gtk.Label();
		this.GtkLabel18.Name = "GtkLabel18";
		this.GtkLabel18.LabelProp = global::Mono.Unix.Catalog.GetString("Quests (read only)");
		this.GtkLabel18.UseMarkup = true;
		this.frame5.LabelWidget = this.GtkLabel18;
		this.vbox1.Add(this.frame5);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.frame5]));
		w39.Position = 4;
		w39.Expand = false;
		w39.Fill = false;
		this.notebook2.Add(this.vbox1);
		// Notebook tab
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Game Data");
		this.notebook2.SetTabLabel(this.vbox1, this.label2);
		this.label2.ShowAll();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeVars = new global::Gtk.TreeView();
		this.treeVars.Sensitive = false;
		this.treeVars.CanFocus = true;
		this.treeVars.Name = "treeVars";
		this.GtkScrolledWindow.Add(this.treeVars);
		this.vbox2.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
		w42.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Value name");
		this.hbox4.Add(this.label7);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label7]));
		w43.Position = 0;
		w43.Expand = false;
		w43.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.txtValueName = new global::Gtk.Entry();
		this.txtValueName.CanFocus = true;
		this.txtValueName.Name = "txtValueName";
		this.txtValueName.IsEditable = true;
		this.txtValueName.InvisibleChar = '•';
		this.hbox4.Add(this.txtValueName);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.txtValueName]));
		w44.Position = 1;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnInsertRaw = new global::Gtk.Button();
		this.btnInsertRaw.CanFocus = true;
		this.btnInsertRaw.Name = "btnInsertRaw";
		this.btnInsertRaw.UseUnderline = true;
		this.btnInsertRaw.Label = global::Mono.Unix.Catalog.GetString("Insert");
		this.hbox4.Add(this.btnInsertRaw);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btnInsertRaw]));
		w45.Position = 2;
		w45.Expand = false;
		w45.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnDeleteRaw = new global::Gtk.Button();
		this.btnDeleteRaw.CanFocus = true;
		this.btnDeleteRaw.Name = "btnDeleteRaw";
		this.btnDeleteRaw.UseUnderline = true;
		this.btnDeleteRaw.Label = global::Mono.Unix.Catalog.GetString("Delete");
		this.hbox4.Add(this.btnDeleteRaw);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btnDeleteRaw]));
		w46.Position = 3;
		w46.Expand = false;
		w46.Fill = false;
		this.vbox2.Add(this.hbox4);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
		w47.Position = 1;
		w47.Expand = false;
		w47.Fill = false;
		this.notebook2.Add(this.vbox2);
		global::Gtk.Notebook.NotebookChild w48 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.vbox2]));
		w48.Position = 1;
		// Notebook tab
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Raw data");
		this.notebook2.SetTabLabel(this.vbox2, this.label3);
		this.label3.ShowAll();
		this.Add(this.notebook2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 624;
		this.DefaultHeight = 747;
		this.notebook2.HasDefault = true;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnOpenPlayerDat.Clicked += new global::System.EventHandler(this.onOpenPlayerDatClick);
		this.btnSave.Clicked += new global::System.EventHandler(this.onSavePlayerDatClick);
		this.cmbScene.Changed += new global::System.EventHandler(this.onSceneChange);
		this.hsAct.ValueChanged += new global::System.EventHandler(this.onActDayChange);
		this.hsDay.ValueChanged += new global::System.EventHandler(this.onActDayChange);
		this.chkNight.Toggled += new global::System.EventHandler(this.onActDayChange);
		this.btnInsertRaw.Clicked += new global::System.EventHandler(this.onInsertRawClick);
		this.btnDeleteRaw.Clicked += new global::System.EventHandler(this.onDeleteRawClick);
	}
}
